In [1]:
import numpy as np

In [11]:
A = np.random.random(size = (4,4))*10
A = np.round(A, 2)
s = np.sum(A, axis = 1)
r = np.sum(A, axis = 0)
print(A)
print(s)
print(r)


[[0.86 8.22 8.52 0.15]
 [6.29 0.68 3.85 6.25]
 [6.02 6.26 3.24 5.51]
 [6.28 4.9  6.54 0.38]]
[17.75 17.07 21.03 18.1 ]
[19.45 20.06 22.15 12.29]


In [12]:
19.45 + 20.06 

39.51

In [31]:

a = [0,-2,3,2,-2, 0]
b = np.conjugate(np.flip(a))
print(np.convolve(a, b))
print(np.linalg.norm(a, ord = 1)**2)
print(np.linalg.norm(np.convolve(a, b), ord = 1))

[  0   0   4 -10  -4  21  -4 -10   4   0   0]
81.0
57.0


In [14]:
np.convolve([0,0,0,1,0], [0,1,0,0,0])

array([0, 0, 0, 0, 1, 0, 0, 0, 0])

In [17]:
(5/2)**2

6.25